In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v0")

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

In [4]:
q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate =0.1
discount_rate = 0.99

exploration_rate  =1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001 #0.01

In [6]:
rewards_all_episodes = []

# Q learning alorithm
for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        # Exploration-exploitation trafeoff
        
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
        
        new_state, reward, done, info = env.step(action)
        
        # Update Q-table for (s,a)
        q_table[state,action] = q_table[state,action] * (1-learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state,:]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done:
            break
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)

## Calculatie and print average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("Average reward per thousand episodes\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ",str(sum(r/1000)))
    count += 1000

# Print updated Q-table
print("\n\n*** Q-table***\n")
print(q_table)

Average reward per thousand episodes

1000 :  0.04300000000000003
2000 :  0.20900000000000016
3000 :  0.43700000000000033
4000 :  0.5300000000000004
5000 :  0.6340000000000005
6000 :  0.6660000000000005
7000 :  0.6780000000000005
8000 :  0.6750000000000005
9000 :  0.6630000000000005
10000 :  0.6760000000000005


*** Q-table***

[[0.5522282  0.4956344  0.5155985  0.51517224]
 [0.29807342 0.28275853 0.35057617 0.5343501 ]
 [0.38285696 0.38308057 0.39792409 0.49434568]
 [0.1756086  0.26950606 0.32035351 0.44951582]
 [0.57703326 0.47922581 0.30669471 0.40198612]
 [0.         0.         0.         0.        ]
 [0.37214938 0.12886286 0.21794337 0.17591051]
 [0.         0.         0.         0.        ]
 [0.43372554 0.42042379 0.37878897 0.610506  ]
 [0.42539246 0.66747879 0.52507913 0.43893864]
 [0.67724896 0.41496711 0.29383803 0.30643755]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.49559704 0.53373013 0.79049072 0.42033854]
 [0.71937855

In [7]:
for episode in range(3):
    state = env.reset()
    done = False
    print("***Episde ",episode+1,"****\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render() ##for visually see agent
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("*** You reached the goal!**")
                time.sleep(3)
            else:
                print("You fell!\n")
                time.sleep(3)
            clear_output(3)
            break
        state = new_state
        
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
*** You reached the goal!**
